# Generated by Django 3.2.15 on 2023-01-16 17:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Production_line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_warehouse', models.CharField(max_length=9, unique=True)),
                ('address_warehouse', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'ordering': ['address_warehouse'],
            },
        ),
        migrations.CreateModel(
            name='Line_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_line', models.CharField(max_length=9)),
                ('address_line', models.CharField(max_length=15)),
                ('line_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='common.production_line')),
                ('transporter_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['address_line'],
            },
        ),
    ]
