# Generated by Django 3.2.15 on 2023-02-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportersLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporter', models.CharField(max_length=30)),
                ('liker_today', models.CharField(max_length=30)),
                ('date_of_like', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['transporter'],
            },
        ),
    ]
