# Generated by Django 3.2.15 on 2023-02-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_number', models.CharField(max_length=9)),
                ('transporter', models.CharField(max_length=30)),
                ('line', models.CharField(max_length=30)),
                ('status_line', models.BooleanField(default=False)),
                ('status_warehouse', models.BooleanField(default=False)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('end_time', models.TimeField(auto_now=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
